"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useAuth } from "../../components/auth-provider";
import { hasSupabaseAuth } from "../../lib/auth";
type Mode = "signin" | "signup";
export default function AuthPage() { const { user, signIn, signUp, signInWithProvider } = useAuth(); const [mode, setMode] = useState<Mode>("signin"); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); useEffect(() => { if (user) window.location.replace("/"); }, [user]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setMessage(""); if (mode === "signup" && name.trim().length < 2) return setError("Please enter your name."); if (password.length < 6) return setError("Use a password with at least 6 characters."); setBusy(true); try { if (mode === "signup") await signUp(name, email, password); else await signIn(email, password); window.location.replace("/"); } catch (reason) { const text = reason instanceof Error ? reason.message : "Authentication failed."; if (mode === "signup" && text.startsWith("Account created")) setMessage(text); else setError(text); } finally { setBusy(false); } }
  async function providerLogin(provider: "google" | "apple" | "github") { setError(""); setBusy(true); try { await signInWithProvider(provider); } catch (reason) { setError(reason instanceof Error ? reason.message : "Provider sign-in failed."); setBusy(false); } }
  return <main className="auth-page"><section className="auth-card"><Link href="/" className="auth-brand"><span className="brand-mark">⌁</span><span>DSA Copilot</span></Link><div className="eyebrow">Your learning workspace</div><h1>{mode === "signin" ? "Welcome back." : "Create your account."}</h1><p className="subtle">{mode === "signin" ? "Sign in to continue your DSA practice." : "Save your progress and keep learning with a personal workspace."}</p><div className="auth-toggle"><button className={mode === "signin" ? "active" : ""} onClick={() => { setMode("signin"); setError(""); }}>Sign in</button><button className={mode === "signup" ? "active" : ""} onClick={() => { setMode("signup"); setError(""); }}>Sign up</button></div><div className="provider-grid"><button className="provider-button" onClick={() => providerLogin("google")} disabled={busy}><b>G</b> Google</button><button className="provider-button" onClick={() => providerLogin("apple")} disabled={busy}><b>●</b> Apple</button><button className="provider-button" onClick={() => providerLogin("github")} disabled={busy}><b>⌘</b> GitHub</button></div><div className="auth-divider"><span>or continue with email</span></div><form onSubmit={submit}>{mode === "signup" && <label>Full name<input value={name} onChange={(event) => setName(event.target.value)} placeholder="Alex Rivera" autoComplete="name" /></label>}<label>Email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" autoComplete="email" required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="At least 6 characters" autoComplete={mode === "signin" ? "current-password" : "new-password"} required /></label>{error && <div className="auth-error">{error}</div>}{message && <div className="auth-message">{message}</div>}<button className="button primary auth-submit" disabled={busy}>{busy ? "Please wait…" : mode === "signin" ? "Sign in" : "Create account"}</button></form><p className="auth-note">{hasSupabaseAuth() ? "Email and social sign-in are connected through Supabase Auth." : "Development mode: email accounts work locally. Add Supabase environment variables to enable social sign-in."}</p></section></main>;
}
